// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmramyidkihevsfsvafc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcmFteWlka2loZXZzZnN2YWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTgwMjcsImV4cCI6MjA3Mzc5NDAyN30.F63ICws2zFOmsYqT-ZvwEeYtu4hKrxipf0nAqnoBGZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});